from typing import Protocol
class SERVICESBASE(Protocol):
    def read_json(self,json_path:str)->dict:
        ...
    def train_data_format(self,json_to_dict:list):
        ...
    def scale_bounding_box(self,box:list[int], width:float, height:float) -> list[int]:
        ...
    def process_bbox(self,box:list):
        ...
    def dataSetFormat(self,img_file):
        ...
    def plot_img(self,im, bbox_list, label_list, prob_list, width, height):
        ...
    def loss_fn(self,pred,target):
        ...
    def __init__(self,json_path,processor=None) -> None:
        ...
    def __len__(self)->int:
        ...
    def __getitem__(self,index)->dict:
        ...
    def convert_bounding_box(self,x, y, width, height):
        ...
    def train_fn(self,data_loader, model, optimizer):
        ...
    def eval_fn(self,data_loader, model):
        ...
    